### ISSUE TITLE
AC unit not turning off using Native version

### ISSUE THREAD

**Issue by madzur** [unixko/MitsuCon#3]
I am using the native MQTT library and I am having a strange issue: 

- The AC unit is not turning off, when I send the off signal from HomeAssistant. 

- Turning on the unit works

- Switching between different modes works as well, however turning off does not. 

- To turn the unit off, I have to use the manual remote control.

Any idea what could be wrong? I’m on HA0.98.2 and the latest ino file downloaded today. I also tried with 0.96.5 and previous ino file version downloaded about a month ago. That yielded the same results, hence my upgrade to the latest versions. That did not help and I’m afraid I won't be revering HA to earlier versions.

**Comment by unixko** [comment]
First please make sure that in HA you're using "climate.set_hvac_mode" to mode "off" in lowercase, not using "climate.turn_off" service. Then use MQTT tool like MQTT Explorer to see what's going on between HA and MitsuCon. Also from MQTT tool you can try to publish command "off" to "heatpump/cmnd/mode" topic to see that MitsuCon alone without HA is working or not.

**Comment by madzur** [comment]
Hi, I’m not exactly sure how to check which mode I’m using, whether it is "climate.set_hvac_mode" or "climate.turn_off". I made no changes to Home Assistant. The unit added itself using autodiscovery from the arduino .ino script.

When I check the MQTT messages and I try to turn the unit off through HomeAssistant the topic "heatpump/cmnd/mode" receives a message "off", which seems to be correct behavior, according to your message. However, the unit physically does not turn off and keeps operating.

Any further tips, please?

**Comment by unixko** [comment]
You didn't mention what is your heat pump model and what is your controller hardware. I suggest you to separate problem by:

1. Check your heat pump model from compatibility list in https://github.com/SwiCago/HeatPump/issues/13 to make sure that your unit is working with SwiCago's library.

2. Try to flash another SwiCago's example code HP_cntrl_Fancy_web.ino to your controller. A controller will act as access point so you can use your phone to control heat pump directly from phone's browser. If it can't turn off, you have to check your controller hardware implementation. If it can turn off, it may be problem in MitsuCon code or MQTT broker.

**Comment by madzur** [comment]
Hello, thanks for your help. Seems the Native code is not in use anymore. I am using Gysmo38's code in the meantime and everything seems to be working well with HA 0.105.5., just like it used to with HA 0.88. You can close the issue. Thanks.
