### ISSUE TITLE
Nest or ecobee 

### ISSUE THREAD

**Issue by IsaacBreuer** [unixko/MitsuCon#4]
I have it working in hass, but I wonder if it possible to ha e it hooked up somehow to a nest or ecobee thermostat

**Comment by unixko** [comment]
I don't have knowledge of those devices so I don't know why you need to use another smart(er?) thermostat to control an already smart heat pump. However, I assumed that you can hook everything up to HA already. Once all of them are in HA, you can use automation to bridge between them. For example, write automation which is triggered when nest/ecobee mode or target temperature changed and then copy that change to heat pump.

**Comment by IsaacBreuer** [comment]
The reason I want to add a mother smart/dumb thermostat, is because if
using hass it relies on wifi and other communication, in case something is
wrong with network the system will run indefinitely and break, but by
having a conventional thermostat it will be handled locally at the heat pump
