### ISSUE TITLE
Enhanced version of MQTT HVAC (Climate platform) with proper History Chart

### ISSUE THREAD

**Issue by dobrynski** [unixko/MitsuCon#7]
FYI, I thought this might be relevant to the target audience here:

https://community.home-assistant.io/t/enhanced-version-of-mqtt-hvac-climate-platform-with-proper-history-chart/75304

**Comment by unixko** [comment]
Previously MQTT HVAC component in HA can only receive device status but cannot send back command to device. So we need a classic version of controller with custom component which is comparable to enhanced version in a link. Now most of functions in that enhanced version are also available in MQTT HVAC component hence it is possible to create native version of MitsuCon code to eliminate using custom component. For activity_state_topic or hvac_action feature, I already implemented it in classic code but am waiting for upstream SwiCago heatpump library update before implementing in native code.
