### ISSUE TITLE
[improvement] Provide way to setup the wifi connection withou using hardcoding

### ISSUE THREAD

**Issue by jmvaz** [unixko/MitsuCon#9]
Try to use some library in order to setup wifi and MQTT connectivity. Example: https://github.com/tzapu/WiFiManager
If we need to change the wifi network or mqtt server we need to reflash the controller.
thanks

**Comment by unixko** [comment]
Thanks for suggestion. For my application, I preferred hardcode since I don't want a risk about configuration reset but I understand your need. @dzungpv already implemented Enhanced code that included WiFiManager and web user interface.

https://github.com/dzungpv/mitsubishi2MQTT
